export const APPWRITE_ENDPOINT = import.meta.env.VITE_APPWRITE_ENDPOINT
export const APPWRITE_PROJECT_ID = import.meta.env.VITE_APPWRITE_PROJECT_ID
export const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID
export const APPWRITE_NEWS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_NEWS_COLLECTION_ID